modules/Web/Routes/web.php
<?php

use Modules\Web\Http\Middleware\IsAdminMiddleware;
use Modules\Account\Models\UserLog;

Route::domain(config('domain.web'))->name('web::')->group(function() {

    Route::get('/', 'Controller@index')->name('index');
    
    Route::get('/about', 'Controller@about')->name('about');
    
    Route::middleware(['auth', IsAdminMiddleware::class])->group(function() {
    	Route::prefix('admin')->namespace('Admin')->name('admin.')->group(function () {
    		// Index
    		Route::redirect('/', '/dashboard')->name("index");
    		// Admin Dashboard
            Route::get('/dashboard', 'DashboardController@dashboard')->name('dashboard');
            // Posts
            Route::put('/posts/{post}/restore', 'PostController@restore')->name('posts.restore');
            Route::delete('/posts/{post}/kill', 'PostController@kill')->name('posts.kill');
            Route::resource('/posts', 'PostController');
            // Comments
            Route::put('/comments/{comment}/approve', 'PostCommentController@approve')->name('comments.approve');
            Route::delete('/comments/{comment}', 'PostCommentController@destroy')->name('comments.destroy');
            // Categories
            Route::resource('/categories', 'CategoryController')->except(['create', 'show']);
            // Users
            Route::put('/users/{user}/repass', 'UserController@repass')->name('users.repass');
            Route::put('/users/{user}/restore', 'UserController@restore')->name('users.restore');
            Route::delete('/users/{user}/kill', 'UserController@kill')->name('users.kill');
            Route::resource('/users', 'UserController');

            Route::get('/logs', function () {
                $logs = UserLog::with('user')->orderByDesc('created_at')->paginate();
                return view('web::admin.logs', compact('logs'));
            })->name('logs');
    	});
    });

    Route::get('/{category}', 'Controller@category')->name('category');
    Route::get('/{category}/{slug}', 'Controller@read')->name('read');
    Route::post('/comments/{post}', 'Controller@comment')->name('comment');
});

modules/Web/Http/Controllers/Admin/CategoryController.php
<?php

namespace Modules\Web\Http\Controllers\Admin;

use Str;
use Modules\Web\Models\BlogCategory;
use Modules\Web\Http\Requests\Admin\Category\StoreRequest;
use Modules\Web\Http\Requests\Admin\Category\UpdateRequest;

use Illuminate\Http\Request;
use Modules\Web\Http\Controllers\Controller;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
    	$categories = BlogCategory::withCount('posts')->when($request->get('search'), function ($query, $v) {
    		return $query->where('name', 'like', '%'.$v.'%');
    	})->orderByDesc('created_at')->paginate($request->get('limit', 10));

        return view('web::admin.categories.index', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreRequest $request)
    {
    	$data = $request->validated();
    	$data['slug'] = Str::slug($data['name']);

        auth()->user()->log('Menambah kategori <strong>'.$data['name'.'</strong>']);

        $category = new BlogCategory($data);
        $category->save();

        return redirect($request->get('next', route('web::admin.categories.index')))
                    ->with('success', 'Kategori berhasil dibuat!');

    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(BlogCategory $category)
    {
    	return view('web::admin.categories.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateRequest $request, BlogCategory $category)
    {
        $data = $request->validated();
    	$data['slug'] = Str::slug($data['name']);

        auth()->user()->log('Mengubah kategori <strong>'.$category->name.'</strong>');

        $category = $category->fill($data);
        $category->save();

        return redirect($request->get('next', route('web::admin.categories.index')))
                    ->with('success', 'Kategori berhasil diperbarui!');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(BlogCategory $category)
    {
        auth()->user()->log('Menghapus kategori <strong>'.$category->title.'</strong>');

        $category->delete();

        return redirect(request('next', route('web::admin.categories.index')))
                    ->with('success', 'Kategori berhasil dihapus!');
    }
}

modules/Web/Resources/views/admin/dashboard.blade.php
@extends('web::layouts.admin')

@section('title', 'Dasbor - ')

@php($user = \Auth::user())

@section('content')
<div class="mb-4">
	<h5 class="mb-0">
		<strong><i class="mdi mdi-home-outline"></i> Dasbor</strong>
	</h5>
</div>
<div class="row">
	<div class="col-lg-8">
		<div class="jumbotron py-5">
			<h4 class="text-dark font-weight-bold">Selamat datang kembali {{ $user->profile->full_name }}!</h4>
			<p class="mb-0">di Halaman Admin Pusat Pengkajian Islam Demokrasi dan Perdamaian</p>
		</div>
		<div class="row mb-4">
			@foreach($categories as $category)
				<div class="col-md-3">
					<div class="card border-0 border-left-dark mb-4">
						<div class="card-body">
							<h3><strong>{{ $category->posts_count }}</strong></h3>
							<small class="text-muted">Jumlah {{ $category->name }} <br></small>
						</div>
					</div>
				</div>
			@endforeach
		</div>
		<div class="card border-0 mb-4">
			<div class="card-header bg-gray-200">
				<i class="mdi mdi-post"></i> Postingan terbaru
			</div>
			@include('web::includes.post-widgets-6', ['post' => $recent_posts])
		</div>
	</div>
	<div class="col-lg-4">
		<div class="card border-0 mb-4">
			<div class="card-header bg-gray-200">
				<i class="mdi mdi-post"></i> Postingan paling banyak dilihat
			</div>
			@include('web::includes.post-widgets-6', ['post' => $most_viewed_posts])
		</div>
		<div class="card border-0 mb-4">
			<div class="card-header bg-gray-200">
				<i class="mdi mdi-account-circle-outline"></i> Akun Anda
			</div>
			<div class="list-group list-group-flush">
				<div class="list-group-item">
					Nama <br>
					<strong>{{ $user->profile->name }}</strong>
				</div>
				<div class="list-group-item">
					Username <br>
					<strong>{{ $user->username }}</strong>
				</div>
				<a class="list-group-item list-group-item-action text-success" href="{{ route('account::index', ['next' => url()->current()]) }}">Selengkapnya &raquo;</a>
			</div>
		</div>
	</div>
</div>
@endsection

modules/Web/Resources/views/admin/logs.blade.php
@extends('web::layouts.admin')

@section('title', 'User log - ')

@php($user = \Auth::user())

@section('content')
<div class="mb-4">
	<h5 class="mb-0">
		<strong><i class="mdi mdi-account-outline"></i> User log</strong>
	</h5>
</div>
<div class="card border-0 mb-4">
	<div class="card-header bg-gray-200">
		<i class="mdi mdi-view-list-outline"></i> User log ({{ $logs->total() }})
	</div>
	<div class="table-responsive">
		<table class="table table-striped table-hover mb-0">
			<thead class="thead-dark">
				<tr>
					<th>No</th>
					<th>Nama</th>
					<th>Log</th>
					<th>Tanggal</th>
				</tr>
			</thead>
			<tbody>
				@forelse($logs as $log)
					<tr>
						<td>{{ $logs->firstItem() + $loop->iteration - 1 }}</td>
						<td><strong>{{ $log->user->profile->name }}</strong></td>
						<td>{!! $log->log !!}</td>
						<td>{{ $log->created_at }}</td>
					</tr>
				@empty
					<tr>
						<td class="text-center" colspan="4">Tidak ada data</td>
					</tr>
				@endforelse
			</tbody>
		</table>
	</div>
	<div class="card-body">
		{{ $logs->appends(request()->all())->links() }}
	</div>
</div>
@endsection