modules/Web/Routes/web.php
<?php

use Modules\Web\Http\Middleware\IsAdminMiddleware;
use Modules\Account\Models\UserLog;

Route::domain(config('domain.web'))->name('web::')->group(function() {

    Route::get('/', 'Controller@index')->name('index');
    
    Route::get('/about', 'Controller@about')->name('about');
    
    Route::middleware(['auth', IsAdminMiddleware::class])->group(function() {
    	Route::prefix('admin')->namespace('Admin')->name('admin.')->group(function () {
    		// Index
    		Route::redirect('/', '/dashboard')->name("index");
    		// Admin Dashboard
            Route::get('/dashboard', 'DashboardController@dashboard')->name('dashboard');
            // Posts
            Route::put('/posts/{post}/restore', 'PostController@restore')->name('posts.restore');
            Route::delete('/posts/{post}/kill', 'PostController@kill')->name('posts.kill');
            Route::resource('/posts', 'PostController');
            // Comments
            Route::put('/comments/{comment}/approve', 'PostCommentController@approve')->name('comments.approve');
            Route::delete('/comments/{comment}', 'PostCommentController@destroy')->name('comments.destroy');
            // Categories
            Route::resource('/categories', 'CategoryController')->except(['create', 'show']);
            // Users
            Route::put('/users/{user}/repass', 'UserController@repass')->name('users.repass');
            Route::put('/users/{user}/restore', 'UserController@restore')->name('users.restore');
            Route::delete('/users/{user}/kill', 'UserController@kill')->name('users.kill');
            Route::resource('/users', 'UserController');

            Route::get('/logs', function () {
                $logs = UserLog::with('user')->orderByDesc('created_at')->paginate();
                return view('web::admin.logs', compact('logs'));
            })->name('logs');
    	});
    });

    Route::get('/{category}', 'Controller@category')->name('category');
    Route::get('/{category}/{slug}', 'Controller@read')->name('read');
    Route::post('/comments/{post}', 'Controller@comment')->name('comment');
});

modules/Web/Http/Controllers/Admin/PostController.php
<?php

namespace Modules\Web\Http\Controllers\Admin;

use Str;
use Storage;
use Modules\Account\Models\User;
use Modules\Web\Models\BlogCategory;
use Modules\Web\Models\BlogPost;
use Modules\Web\Models\BlogPostComment;
use Modules\Web\Http\Requests\Admin\Post\StoreRequest;
use Modules\Web\Http\Requests\Admin\Post\UpdateRequest;

use Illuminate\Http\Request;
use Modules\Web\Http\Controllers\Controller;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
    	$posts = BlogPost::withCount('unpublishedComments')->with('categories')->when($request->get('search'), function ($query, $v) {
    		return $query->where('title', 'like', '%'.$v.'%');
    	})->when($request->get('category'), function ($query, $v) {
    		return $query->whereHas('categories', function ($category) use ($v) {
                return $category->where('id', $v);
            });
    	})->when($request->get('trashed'), function ($query, $v) {
    		return $query->onlyTrashed();
    	})->orderByDesc('created_at')->paginate($request->get('limit', 10));

    	$categories = BlogCategory::all();

        $latest_comments = BlogPostComment::orderByDesc('created_at')->limit(5)->get();

        return view('web::admin.posts.index', compact('posts', 'categories', 'latest_comments'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
    	$categories = BlogCategory::all();
        $authors = User::whereAdmin()->get();

    	return view('web::admin.posts.create', compact('categories', 'authors'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreRequest $request)
    {
        $content = BlogPost::makeContent($request->input('content'));

        $cover = $request->has('file')
                    ? $request->file('file')->store('blogs/'.date('Ymd'))
                    : null;

        $post = new BlogPost([
            'title'             => $request->input('title'),
            'img'               => $cover,
            'content'           => $content,
            'author_id'         => $request->input('author_id'),
            'commentable'       => $request->input('commentable', 0),
            'visibled'          => 1,
            'published_at'      => $request->input('published_at'),
        ]);

        $post->save();
        $post->categories()->sync($request->input('categories'));

        auth()->user()->log('Membuat postingan <strong>'.$post->title.'</strong>');

        return redirect($request->get('next', route('web::admin.posts.index')))
                    ->with('success', 'Postingan berhasil dibuat!');

    }

    /**
     * Show the specified resource.
     */
    public function show(Request $request, BlogPost $post)
    {
        $post->load('comments');

        return view('web::admin.posts.show', compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(BlogPost $post)
    {
    	$categories = BlogCategory::all();
        $authors = User::whereAdmin()->get();

    	return view('web::admin.posts.edit', compact('post', 'categories', 'authors'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateRequest $request, BlogPost $post)
    {
        $content = BlogPost::makeContent($request->input('content'));
        $cover = $request->has('file')
                    ? Storage::putFile('blogs/'.date('Ymd'), $request->file('file'))
                    : null;

        $post = $post->fill([
            'title'             => $request->input('title'),
            'img'               => $cover ?? $post->img,
            'content'           => $content,
            'author_id'         => $request->post('author_id'),
            'commentable'       => $request->input('commentable', 0),
            'visibled'          => 1,
            'published_at'      => $request->input('published_at'),
        ]);

        $post->save();
        $post->categories()->sync($request->input('categories'));

        auth()->user()->log('Mengubah postingan <strong>'.$post->title.'</strong>');

        return redirect($request->get('next', route('web::admin.posts.index')))
                    ->with('success', 'Postingan berhasil diperbarui!');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(BlogPost $post)
    {
        $post->delete();

        auth()->user()->log('Membuang postingan <strong>'.$post->title.'</strong>');

        return redirect(request('next', route('web::admin.posts.index')))
                    ->with('success', 'Postingan berhasil dibuang!');
    }

    /**
     * Restore the specified resource from storage.
     */
    public function restore(BlogPost $post)
    {
        $post->restore();

        auth()->user()->log('Memulihkan postingan <strong>'.$post->title.'</strong>');

        return redirect(request('next', route('web::admin.posts.index')))
                    ->with('success', 'Postingan berhasil dipulihkan!');
    }

    /**
     * Kill the specified resource from storage.
     */
    public function kill(BlogPost $post)
    {
        auth()->user()->log('Menghapus postingan <strong>'.$post->title.'</strong>');

        $post->forceDelete();

        return redirect(request('next', route('web::admin.posts.index')))
                    ->with('success', 'Postingan berhasil dihapus secara permanen!');
    }
}

modules/Web/Resources/views/admin/posts/create.blade.php
@extends('web::layouts.admin')

@section('title', 'Buat postingan baru - ')

@php($url = url()->current())

@section('content')
<div class="mb-4">
	<h5 class="mb-0">
		<a href="{{ request('next', route('web::admin.posts.index')) }}"><i class="mdi mdi-arrow-left-circle-outline"></i></a>
		<strong>Buat postingan baru</strong>
	</h5>
</div>
<form class="form-block" action="{{ route('web::admin.posts.store') }}" method="POST" enctype="multipart/form-data" id="create_post"> @csrf
	<div class="row">
		<div class="col-lg-4">
			<div class="card border-0 mb-4">
				<div class="card-body">
					<div class="form-group">
						<label>Kategori</label>
						<div class="rounded border @error('categories') border-danger @enderror p-2">
							@foreach($categories as $category)
								<div class="custom-control custom-checkbox">
									<input type="checkbox" class="custom-control-input" name="categories[]" id="category{{ $category->id }}" value="{{ $category->id }}" @if(in_array($category->id, old('categories', []))) checked @endif>
									<label class="custom-control-label" for="category{{ $category->id }}">{{ $category->name }}</label>
								</div>
							@endforeach
						</div>
						@error('categories')
							<small class="text-danger">{{ $message }}</small>
						@enderror
					</div>
					<div class="form-group">
						<label>Penulis</label>
						<select type="text" class="form-control @error('author_id') is-invalid @enderror" name="author_id">
							<option value="">-- Pilih --</option>
							@foreach($authors as $author)
								<option value="{{ $author->id }}" @if(old('author_id', auth()->id())) selected @endif>{{ $author->profile->name }} ({{ $author->username }})</option>
							@endforeach
						</select>
						@error('author_id')
							<span class="invalid-feedback">{{ $message }}</span>
						@enderror
					</div>
					<div class="form-group">
						<label>Waktu publish</label>
						<input type="date" class="form-control @error('published_at') is-invalid @enderror" name="published_at" value="{{ date('Y-m-d') }}">
						@error('published_at')
							<span class="invalid-feedback">{{ $message }}</span>
						@enderror
					</div>
					<label>Foto cover</label>
					<div class="border @error('file') border-danger @enderror rounded text-center mb-3">
						<img id="upload-preview" class="img-fluid" src="{{ asset('img/no-image.png') }}" alt="" style="max-height: 224px;">
					</div>
					<div class="form-group">
						<div class="input-group">
							<div class="custom-file">
								<input type="file" name="file" class="custom-file-input" id="upload-input" accept="image/*">
								<label class="custom-file-label" for="upload-input">Pilih cover ...</label>
							</div>
						</div>
						@error('file')
							<small class="text-danger"> {{ $message }} </small>
						@enderror
					</div>
				</div>
			</div>
		</div>
		<div class="col-lg-8 order-lg-first">
			<div class="card border-0 mb-4">
				<div class="card-body">
					<div class="form-group">
						<input type="text" class="form-control @error('title') is-invalid @enderror" name="title" placeholder="Judul postingan" value="{{ old('title') }}" autofocus required>
						@error('title')
							<span class="invalid-feedback">{{ $message }}</span>
						@enderror
					</div>
					<div class="form-group">
						<textarea name="content" class="summernote">
							{{ old('content') }}
						</textarea>
						@error('content')
							<span class="invalid-feedback">{{ $message }}</span>
						@enderror
					</div>
					<div class="form-group">
						<div class="custom-control custom-checkbox">
							<input type="checkbox" class="custom-control-input" id="commentable" checked name="commentable" value="1">
							<label class="custom-control-label" for="commentable">Centang untuk mengaktifkan fitur komentar</label>
						</div>
					</div>
					<div class="form-group mb-0">
						<button type="submit" class="btn btn-success"><i class="mdi mdi-check"></i> Publish</button>
						<button type="button" class="btn btn-warning" id="save_as_draft"><i class="mdi mdi-content-save-outline"></i> Simpan sebagai draft</button>
						<a class="btn btn-secondary" href="{{ request('next', route('web::admin.posts.index')) }}"><i class="mdi mdi-arrow-left"></i> Kembali</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</form>
@endsection

@push('style')
	<link rel="stylesheet" href="{{ asset('css/summernote.min.css') }}">
@endpush

@push('script')
<script src="{{ asset('js/summernote.min.js') }}"></script>
<script>
	$(() => {
		$('.summernote').summernote({
			placeholder: 'Tulis isi postingan disini ...',
			height: 250
		});
		$('#save_as_draft').click(() => {
			if (confirm('Apakah Anda yakin?')) {
				$('[name="published_at"]').val('')
				$('#create_post').submit();
			}
		});
		function readURL(input) {
			if (input.files && input.files[0]) {
				$('[for="upload-input"]').html(input.files[0].name)
				var reader = new FileReader();
				reader.onload = function(e) {
					$('#upload-preview').attr('src', e.target.result);
				}
				reader.readAsDataURL(input.files[0]);
			}
		}

		$("#upload-input").change(function(e) {
			readURL(this);
		});
	})
</script>
@endpush

modules/Web/Resources/views/admin/posts/edit.blade.php
@extends('web::layouts.admin')

@section('title', 'Edit postingan - ')

@php($url = url()->current())

@section('content')
<div class="mb-4">
	<h5 class="mb-0">
		<a href="{{ request('next', route('web::admin.posts.index')) }}"><i class="mdi mdi-arrow-left-circle-outline"></i></a>
		<strong>Edit postingan</strong>
	</h5>
</div>
<form class="form-block" action="{{ route('web::admin.posts.update', ['post' => $post->id]) }}" method="POST" enctype="multipart/form-data" id="edit_post"> @csrf @method('PUT')
	<div class="row">
		<div class="col-lg-4">
			<div class="card border-0 mb-4">
				<div class="card-body">
					<div class="form-group">
						<label>Kategori</label>
						<div class="rounded border @error('categories') border-danger @enderror p-2">
							@foreach($categories as $category)
								<div class="custom-control custom-checkbox">
									<input type="checkbox" class="custom-control-input" name="categories[]" id="category{{ $category->id }}" value="{{ $category->id }}" @if(in_array($category->id, old('categories', $post->categories->pluck('id')->toArray() ?? []))) checked @endif>
									<label class="custom-control-label" for="category{{ $category->id }}">{{ $category->name }}</label>
								</div>
							@endforeach
						</div>
						@error('categories')
							<small class="text-danger">{{ $message }}</small>
						@enderror
					</div>
					<div class="form-group">
						<label>Penulis</label>
						<select type="text" class="form-control @error('author_id') is-invalid @enderror" name="author_id">
							<option value="">-- Pilih --</option>
							@foreach($authors as $author)
								<option value="{{ $author->id }}" @if(old('author_id', $post->author_id)) selected @endif>{{ $author->profile->name }} ({{ $author->username }})</option>
							@endforeach
						</select>
						@error('author_id')
							<span class="invalid-feedback">{{ $message }}</span>
						@enderror
					</div>
					<div class="form-group">
						<label>Waktu publish</label>
						<input type="date" class="form-control @error('published_at') is-invalid @enderror" name="published_at" value="{{ $post->published_at ? $post->published_at->format('Y-m-d') : date('Y-m-d') }}">
						@error('published_at')
							<span class="invalid-feedback">{{ $message }}</span>
						@enderror
					</div>
					<label>Foto cover</label>
					<div class="border @error('file') border-danger @enderror rounded text-center mb-3">
						<img id="upload-preview" class="img-fluid" src="{{ $post->img ? Storage::url($post->img) : asset('img/no-image.png') }}" alt="" style="max-height: 224px;">
					</div>
					<div class="form-group">
						<div class="input-group">
							<div class="custom-file">
								<input type="file" name="file" class="custom-file-input" id="upload-input" accept="image/*">
								<label class="custom-file-label" for="upload-input">Pilih cover ...</label>
							</div>
						</div>
						@error('file')
							<small class="text-danger"> {{ $message }} </small>
						@enderror
					</div>
				</div>
			</div>
		</div>
		<div class="col-lg-8 order-lg-first">
			<div class="card border-0 mb-4">
				<div class="card-body">
					<div class="form-group">
						<input type="text" class="form-control @error('title') is-invalid @enderror" name="title" placeholder="Judul postingan" value="{{ old('title', $post->title) }}" autofocus required>
						@error('title')
							<span class="invalid-feedback">{{ $message }}</span>
						@enderror
					</div>
					<div class="form-group">
						<textarea name="content" class="summernote">
							{{ old('content', $post->content) }}
						</textarea>
						@error('content')
							<span class="invalid-feedback">{{ $message }}</span>
						@enderror
					</div>
					<div class="form-group">
						<div class="custom-control custom-checkbox">
							<input type="checkbox" class="custom-control-input" id="commentable" name="commentable" value="1" @if(old('commentable', $post->commentable == 1 ? 1 : 0)) checked @endif>
							<label class="custom-control-label" for="commentable">Centang untuk mengaktifkan fitur komentar</label>
						</div>
					</div>
					<div class="form-group mb-0">
						<button type="submit" class="btn btn-success"><i class="mdi mdi-check"></i> Publish</button>
						<a class="btn btn-secondary" href="{{ request('next', route('web::admin.posts.index')) }}"><i class="mdi mdi-arrow-left"></i> Kembali</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</form>
@endsection

@push('style')
	<link rel="stylesheet" href="{{ asset('css/summernote.min.css') }}">
@endpush

@push('script')
<script src="{{ asset('js/summernote.min.js') }}"></script>
<script>
	$(() => {
		$('.summernote').summernote({
			placeholder: 'Tulis isi postingan disini ...',
			height: 250
		});
		function readURL(input) {
			if (input.files && input.files[0]) {
				$('[for="upload-input"]').html(input.files[0].name)
				var reader = new FileReader();
				reader.onload = function(e) {
					$('#upload-preview').attr('src', e.target.result);
				}
				reader.readAsDataURL(input.files[0]);
			}
		}

		$("#upload-input").change(function(e) {
			readURL(this);
		});
	})
</script>
@endpush

modules/Web/Resources/views/admin/posts/index.blade.php
@extends('web::layouts.admin')

@section('title', 'Postingan - ')

@php($url = url()->current())

@section('content')
<div class="mb-4">
	<h5 class="mb-0">
		<strong><i class="mdi mdi-newspaper"></i> Postingan</strong>
	</h5>
</div>
<div class="mb-4">
	<a class="btn btn-success" href="{{ route('web::admin.posts.create', ['next' => $url]) }}"><i class="mdi mdi-plus-circle-outline"></i> Buat postingan baru</a>
</div>
<div class="row">
	<div class="col-lg-8">
		<div class="card border-0 mb-4">
			<div class="card-header bg-gray-200">
				<i class="mdi mdi-view-list-outline"></i> Daftar postingan
			</div>
			<div class="card-body">
				<form class="form-block" action="{{ route('web::admin.posts.index') }}" method="GET">
					<div class="input-group">
						<input type="hidden" name="category" value="{{ request('category') }}">
						<input type="hidden" name="trashed" value="{{ request('trashed') }}">
						<input class="form-control" type="search" name="search" placeholder="Cari judul disini..." value="{{ request('search') }}">
						<div class="input-group-append">
							<a class="btn btn-light border" href="{{ route('web::admin.posts.index') }}"><i class="mdi mdi-refresh"></i></a>
							<button class="btn btn-dark"><i class="mdi mdi-magnify"></i></button>
						</div>
					</div>
				</form>
			</div>
			<div class="table-responsive">
				<table class="table table-striped table-hover mb-0">
					<thead class="thead-dark">
						<tr>
							<th>No</th>
							<th>Judul</th>
							<th>Kategori</th>
							<th>Dipublikasi</th>
							<th></th>
						</tr>
					</thead>
					<tbody>
						@forelse($posts as $post)
							<tr>
								<td class="align-middle">{{ $posts->firstItem() + $loop->iteration - 1 }}</td>
								<td style="min-width: 300px;">
									<strong>{{ $post->title }}</strong>
									@if($post->unpublished_comments_count)
										<a href="{{ route('web::admin.posts.show', ['post' => $post->id, 'next' => url()->current()]) }}">
											<span class="badge badge-pill badge-danger"><i class="mdi mdi-comment-alert"></i> {{ $post->unpublished_comments_count }}</span>
										</a>
									@endif
									<br>
									@if($post->trashed())
										@canany(['author', 'editor', 'administrator'])
											<form class="d-inline form-confirm form-block" action="{{ route('web::admin.posts.restore', ['post' => $post->id]) }}" method="POST"> @csrf @method('PUT')
												<button class="btn btn-link align-baseline text-success p-0 mr-2">Pulihkan</button>
											</form>
											@can('administrator')
												<form class="d-inline form-confirm form-block" action="{{ route('web::admin.posts.kill', ['post' => $post->id]) }}" method="POST"> @csrf @method('DELETE')
													<button class="btn btn-link align-baseline text-danger p-0 mr-2">Hapus permanen</button>
												</form>
											@endcanany
										@endcanany
									@else
										@canany(['editor', 'administrator'])
											<a class="mr-2" href="{{ route('web::admin.posts.edit', ['post' => $post->id, 'next' => url()->current()]) }}">Edit</a>
											<form class="d-inline form-confirm form-block" action="{{ route('web::admin.posts.destroy', ['post' => $post->id]) }}" method="POST"> @csrf @method('DELETE')
												<button class="btn btn-link align-baseline text-danger p-0 mr-2">Buang</button>
											</form>
										@endcanany
										<a href="{{ route('web::read', ['category' => $post->category()->slug, 'slug' => $post->slug, 'next' => $url]) }}" target="_blank">Lihat</a>
									@endif
								</td>
								<td class="align-middle" style="max-width: 200px;">
									<div>
										@forelse($post->categories->take(3) as $category)
											<span class="badge badge-pill badge-dark">{{ $category->name }}</span>
										@empty
											<span class="badge badge-pill badge-secondary">Uncategorized</span>
										@endforelse
									</div>
								</td>
								<td class="align-middle">
									<small>{{ $post->published_at ? $post->published_at->ISOFormat('L') : '-' }}</small><br>
									<i class="mdi mdi-eye"></i> <small>{{ $post->views_count }}</small>
									{{-- <i class="mdi mdi-heart"></i> <small>{{ $post->likes_count }}</small> --}}
									<i class="mdi {{ $post->commentable ? 'mdi-comment' : 'mdi-comment-remove' }}"></i> <small>{{ $post->comments_count }}</small>
								</td>
								<td class="align-middle">
									@if(!$post->trashed())
										<a class="btn btn-primary btn-sm rounded-pill text-nowrap" href="{{ route('web::admin.posts.show', ['post' => $post->id, 'next' => url()->current()]) }}"><i class="mdi mdi-eye-outline"></i> Detail</a>
									@endif
								</td>
							</tr>
						@empty
							<tr>
								<td class="text-center" colspan="5">Tidak ada data</td>
							</tr>
						@endforelse
					</tbody>
				</table>
			</div>
			<div class="card-body">
				{{ $posts->appends(request()->all())->links() }}
			</div>
		</div>
	</div>
	<div class="col-lg-4">
		<div class="card border-0 mb-4">
			<div class="card-header bg-gray-200">
				<i class="mdi mdi-filter-outline"></i> Filter
			</div>
			<div class="card-body">
				<form class="form-block" action="{{ route('web::admin.posts.index') }}" method="get">
					<div class="form-group">
						<select type="text" class="form-control" name="category">
							<option value="">Semua kategori</option>
							@foreach($categories as $category)
								<option value="{{ $category->id }}" @if(request('category') == $category->id) selected @endif>{{ $category->name }}</option>
							@endforeach
						</select>
					</div>
					<div class="form-group mb-0">
						<button type="submit" class="btn btn-dark">Tetapkan</button>
					</div>
				</form>
			</div>
		</div>
		<div class="card border-0 mb-4">
			<div class="card-header bg-gray-200">
				<i class="mdi mdi-comment-multiple"></i> Komentar terakhir
			</div>
			@include('web::includes.comment-widgets-1', ['comments' => $latest_comments])
		</div>
		<div class="card border-0 mb-4">
			<div class="card-header bg-gray-200">
				<i class="mdi mdi-cogs"></i> Lanjutan
			</div>
			<div class="list-group list-group-flush">
				<a class="list-group-item list-group-item-action text-danger" href="{{ route('web::admin.posts.index', ['category' => request('category'), 'trashed' => request('trashed') ? 0 : 1 ]) }}">
					<i class="mdi mdi-trash-can-outline"></i>Tampilkan postingan yang {{ request('trashed') ? 'tidak' : '' }} dihapus
				</a>
			</div>
		</div>
	</div>
</div>
@endsection

modules/Web/Resources/views/admin/posts/show.blade.php
@extends('web::layouts.admin')

@section('title', 'Detail postingan - ')

@php($url = url()->current())

@section('content')
<div class="mb-4">
	<h5 class="mb-0">
		<a href="{{ request('next', route('web::admin.posts.index')) }}"><i class="mdi mdi-arrow-left-circle-outline"></i></a>
		<strong>Detail postingan</strong>
	</h5>
</div>
<div class="row">
	<div class="col-md-8">
		<div class="row mb-4 d-flex align-items-center">
			<div class="col-lg-4">
				<div class="rounded mb-4 mb-lg-0" style="background: url({{ Storage::url($post->img) }}) center center no-repeat; background-size: cover; height: 200px;"></div>
			</div>
			<div class="col-lg-8">
				<div class="bg-white rounded p-4">
					<div class="mb-2">
						@forelse($post->categories->take(3) as $category)
							<span class="badge badge-pill badge-dark">{{ $category->name }}</span>
						@empty
							<span class="badge badge-pill badge-secondary">Uncategorized</span>
						@endforelse
					</div>
					<h5><strong>{{ $post->title }}</strong></h5>
					<div class="text-muted">
						<i class="mdi mdi-eye"></i> <small>{{ $post->views_count }}</small>
						{{-- <i class="mdi mdi-heart"></i> <small>{{ $post->likes_count }}</small> --}}
						<i class="mdi {{ $post->commentable ? 'mdi-comment' : 'mdi-comment-remove' }}"></i> <small>{{ $post->comments_count }}</small>
						<i class="mdi mdi-calendar"></i> <small>{{ $post->created_at ? $post->created_at->ISOFormat('L') : '-' }}</small>
					</div>
					<div class="text-muted mb-2">{{ \Str::words(strip_tags($post->content), 20) }}</div>
					<div>
						@canany(['editor', 'administrator'])
							<a class="mr-2" href="{{ route('web::admin.posts.edit', ['post' => $post->id, 'next' => url()->current()]) }}">Edit</a>
							<form class="d-inline form-confirm form-block" action="{{ route('web::admin.posts.destroy', ['post' => $post->id]) }}" method="POST"> @csrf @method('DELETE')
								<button class="btn btn-link align-baseline text-danger p-0 mr-2">Buang</button>
							</form>
						@endcanany
						<a href="{{ route('web::read', ['category' => $post->category()->slug, 'slug' => $post->slug, 'next' => $url]) }}" target="_blank">Lihat</a>
					</div>
				</div>
			</div>
		</div>
		<div class="card border-0 mb-4">
			<div class="card-header bg-gray-200">
				<i class="mdi mdi-comment-multiple"></i> Komentar
			</div>
			<div class="list-group list-group-flush">
				@forelse($post->comments as $comment)
					<div class="list-group-item">
						<section class="d-flex flex-row w-100">
							<div>
								<img class="rounded-circle mr-3" src="{{ $comment->commentator->profile->avatar_path }}" alt="" style="width: 46px;">
							</div>
							<div class="flex-grow-1 bg-light rounded p-3">
								<div class="font-weight-bold">{{ $comment->commentator->profile->full_name }}</div>
								<article class="comments-readmore overflow-hidden">{{ $comment->content }}</article>
								<small class="text-muted"><i class="mdi mdi-calendar-outline"></i> {{ $comment->created_at->ISOFormat('llll') }}</small>
								<div class="mt-2">
									<form class="d-inline form-block form-confirm" action="{{ route('web::admin.comments.approve', ['comment' => $comment->id, 'next' => url()->current()]) }}" method="post"> @csrf @method('PUT')
										<button class="btn btn-{{ $comment->published_at ? 'warning' : 'success' }} btn-sm"><i class="mdi mdi-{{ $comment->published_at ? 'close' : 'check' }}-circle-outline"></i> {{ $comment->published_at ? 'Reject' : 'Approve' }}</button>
									</form>
									<form class="d-inline form-block form-confirm" action="{{ route('web::admin.comments.destroy', ['comment' => $comment->id, 'next' => url()->current()]) }}" method="post"> @csrf @method('DELETE')
										<button class="btn btn-danger btn-sm"><i class="mdi mdi-trash-can"></i> Hapus <span class="d-none d-sm-inline">komentar</span></button>
									</form>
								</div>
							</div>
						</section>
					</div>
				@empty
					<div class="list-group-item">Tidak ada komentar</div>
				@endforelse
			</div>
		</div>
	</div>
	<div class="col-md-4">
		<div class="card border-0 mb-4">
			<div class="card-header bg-gray-200">
				<i class="mdi mdi-newspaper"></i> Detail postingan
			</div>
			<div class="list-group list-group-flush">
				@foreach([
						'Author'	=> $post->author->profile->full_name ?? null,
						'Waktu publish'	=> $post->published_at ? $post->published_at->ISOFormat('LL') : null,
						'Dibuat pada'	=> $post->created_at,
						'Terakhir diperbarui'	=> $post->updated_at,
					] as $k => $v)
					<div class="list-group-item">
						<small>{{ $k }} </small><br> <strong>{!! $v ?? '-' !!}</strong>
					</div>
				@endforeach
			</div>
		</div>
	</div>
</div>
@endsection

@push('script')
<script src="{{ asset('js/readmore.min.js') }}"></script>
<script>
	$(() => {
		$('.comments-readmore').readmore({collapsedHeight:70});
	})
</script>
@endpush